// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251122125930_InitialCreateIdentity")]
    partial class InitialCreateIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Entity.ContentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.HasKey("Id")
                        .HasName("pk_content");

                    b.ToTable("content", "identity");
                });

            modelBuilder.Entity("Database.Entity.ImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("large_id");

                    b.Property<Guid>("MediumId")
                        .HasColumnType("uuid")
                        .HasColumnName("medium_id");

                    b.Property<Guid>("SmallId")
                        .HasColumnType("uuid")
                        .HasColumnName("small_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_image");

                    b.HasIndex("LargeId")
                        .HasDatabaseName("ix_image_large_id");

                    b.HasIndex("MediumId")
                        .HasDatabaseName("ix_image_medium_id");

                    b.HasIndex("SmallId")
                        .HasDatabaseName("ix_image_small_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_image_user_id");

                    b.ToTable("image", "identity");
                });

            modelBuilder.Entity("Database.Entity.LoginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("boolean")
                        .HasColumnName("first_login");

                    b.Property<Guid>("OAuthProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("o_auth_process_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login");

                    b.HasIndex("OAuthProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_login_o_auth_process_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_user_id");

                    b.ToTable("login", "identity");
                });

            modelBuilder.Entity("Database.Entity.OAuthProcessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthenticationProvider")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("authentication_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("error");

                    b.Property<string>("ErrorRedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_redirect_uri");

                    b.Property<string>("FullUserJson")
                        .HasMaxLength(2147483647)
                        .HasColumnType("jsonb")
                        .HasColumnName("full_user_json");

                    b.Property<Guid?>("LoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_id");

                    b.Property<string>("LoginRedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_redirect_uri");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("state");

                    b.Property<string>("SuccessRedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("success_redirect_uri");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_o_auth_process");

                    b.HasIndex("State")
                        .IsUnique()
                        .HasDatabaseName("ix_o_auth_process_state");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_o_auth_process_user_id");

                    b.ToTable("o_auth_process", "identity");
                });

            modelBuilder.Entity("Database.Entity.RefreshEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HashedRefreshToken")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("hashed_refresh_token");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_id");

                    b.Property<string>("RemoteIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("remote_ip_address");

                    b.Property<int>("RemotePort")
                        .HasColumnType("integer")
                        .HasColumnName("remote_port");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_refresh");

                    b.HasIndex("LoginId")
                        .HasDatabaseName("ix_refresh_login_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_user_id");

                    b.ToTable("refresh", "identity");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthenticationProvider")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("authentication_provider");

                    b.Property<string>("AuthenticationProviderId")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("authentication_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<int>("ImageProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("image_processing_attempts");

                    b.Property<string>("RawAvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_avatar_url");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "identity");
                });

            modelBuilder.Entity("Database.Entity.ImageEntity", b =>
                {
                    b.HasOne("Database.Entity.ContentEntity", "Large")
                        .WithMany()
                        .HasForeignKey("LargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_content_large_id");

                    b.HasOne("Database.Entity.ContentEntity", "Medium")
                        .WithMany()
                        .HasForeignKey("MediumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_content_medium_id");

                    b.HasOne("Database.Entity.ContentEntity", "Small")
                        .WithMany()
                        .HasForeignKey("SmallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_content_small_id");

                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithOne("Image")
                        .HasForeignKey("Database.Entity.ImageEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_user_user_id");

                    b.Navigation("Large");

                    b.Navigation("Medium");

                    b.Navigation("Small");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.LoginEntity", b =>
                {
                    b.HasOne("Database.Entity.OAuthProcessEntity", "OAuthProcess")
                        .WithOne("Login")
                        .HasForeignKey("Database.Entity.LoginEntity", "OAuthProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_o_auth_process_o_auth_process_id");

                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany("Login")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_user_user_id");

                    b.Navigation("OAuthProcess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.OAuthProcessEntity", b =>
                {
                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_o_auth_process_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.RefreshEntity", b =>
                {
                    b.HasOne("Database.Entity.LoginEntity", "Login")
                        .WithMany("Refresh")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_login_login_id");

                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany("Refresh")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_user_user_id");

                    b.Navigation("Login");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.LoginEntity", b =>
                {
                    b.Navigation("Refresh");
                });

            modelBuilder.Entity("Database.Entity.OAuthProcessEntity", b =>
                {
                    b.Navigation("Login");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Login");

                    b.Navigation("Refresh");
                });
#pragma warning restore 612, 618
        }
    }
}
