// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251019175504_InitialCreateIdentity")]
    partial class InitialCreateIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Entity.AccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_id");

                    b.Property<Guid>("RefreshId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_id");

                    b.Property<string>("RemoteIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("remote_ip_address");

                    b.Property<int>("RemotePort")
                        .HasColumnType("integer")
                        .HasColumnName("remote_port");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access");

                    b.HasIndex("LoginId")
                        .HasDatabaseName("ix_access_login_id");

                    b.HasIndex("RefreshId")
                        .HasDatabaseName("ix_access_refresh_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_user_id");

                    b.ToTable("access", "identity");
                });

            modelBuilder.Entity("Database.Entity.ContentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.HasKey("Id")
                        .HasName("pk_content");

                    b.ToTable("content", "identity");
                });

            modelBuilder.Entity("Database.Entity.LoginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LoginProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_process_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login");

                    b.HasIndex("LoginProcessId")
                        .IsUnique()
                        .HasDatabaseName("ix_login_login_process_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_user_id");

                    b.ToTable("login", "identity");
                });

            modelBuilder.Entity("Database.Entity.OAuthProcessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("error");

                    b.Property<string>("ErrorRedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_redirect_uri");

                    b.Property<Guid?>("LoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("state");

                    b.Property<string>("SuccessRedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("success_redirect_uri");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_o_auth_process");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_o_auth_process_user_id");

                    b.ToTable("o_auth_process", "identity");
                });

            modelBuilder.Entity("Database.Entity.RefreshEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_id");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("RemoteIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("remote_ip_address");

                    b.Property<int>("RemotePort")
                        .HasColumnType("integer")
                        .HasColumnName("remote_port");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh");

                    b.HasIndex("LoginId")
                        .HasDatabaseName("ix_refresh_login_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_user_id");

                    b.ToTable("refresh", "identity");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthenticationProvider")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("authentication_provider");

                    b.Property<string>("AuthenticationProviderId")
                        .IsRequired()
                        .HasMaxLength(1028)
                        .HasColumnType("character varying(1028)")
                        .HasColumnName("authentication_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "identity");
                });

            modelBuilder.Entity("Database.Entity.AccessEntity", b =>
                {
                    b.HasOne("Database.Entity.LoginEntity", "Login")
                        .WithMany("Access")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_login_login_id");

                    b.HasOne("Database.Entity.RefreshEntity", "Refresh")
                        .WithMany("Access")
                        .HasForeignKey("RefreshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_refresh_refresh_id");

                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany("Access")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_access_user_user_id");

                    b.Navigation("Login");

                    b.Navigation("Refresh");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.LoginEntity", b =>
                {
                    b.HasOne("Database.Entity.OAuthProcessEntity", "LoginProcess")
                        .WithOne("Login")
                        .HasForeignKey("Database.Entity.LoginEntity", "LoginProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_o_auth_process_login_process_id");

                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany("Login")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_user_user_id");

                    b.Navigation("LoginProcess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.OAuthProcessEntity", b =>
                {
                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_o_auth_process_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.RefreshEntity", b =>
                {
                    b.HasOne("Database.Entity.LoginEntity", "Login")
                        .WithMany("Refresh")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_login_login_id");

                    b.HasOne("Database.Entity.UserEntity", "User")
                        .WithMany("Refresh")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_user_user_id");

                    b.Navigation("Login");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Entity.LoginEntity", b =>
                {
                    b.Navigation("Access");

                    b.Navigation("Refresh");
                });

            modelBuilder.Entity("Database.Entity.OAuthProcessEntity", b =>
                {
                    b.Navigation("Login");
                });

            modelBuilder.Entity("Database.Entity.RefreshEntity", b =>
                {
                    b.Navigation("Access");
                });

            modelBuilder.Entity("Database.Entity.UserEntity", b =>
                {
                    b.Navigation("Access");

                    b.Navigation("Login");

                    b.Navigation("Refresh");
                });
#pragma warning restore 612, 618
        }
    }
}
